baseURL = "https://sjsu-dev2.github.io/libembeddedhal/"
languageCode = "en-us"
title = "libembeddedhal docs"
theme = "hugo-theme-relearn"

[params]
  themeVariant = "green"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
